### ISSUE TITLE
further packages are needed to build

### ISSUE THREAD

**Issue by stegro** [1and1/debianized-jupyterhub#2]
It seems, further packages are needed to build using `./build.sh debian:stretch`, namely `python-setuptools`, `libparse-debianchangelog-perl` and `debhelper`.

**Comment by jhermann** [comment]
All those are in the list in "Dockerfile.build", you have to provide more info on what exactly you did and what the output was.

Also: “works for me”, so what do you have different?

**Comment by jhermann** [comment]
@stegro Please confirm it was a docs omission (see commit).

**Comment by stegro** [comment]
Hello @jhermann , thanks for asking. I startet from a clean new Debian installation and I had to install these, in order to let `./build.sh debian:stretch` finish. Unfortunately on this new machine the terminal emulator did not keep enough lines so that I do not have the error messages any more. I would have to deinstall the packages and cleanup the build, to reproduce them, I guess. I'll do it if I find some time these days.
No, I did not use the `debian:buster` argument and the ``command . .env --yes`` call, indeed. Thanks for pointing them out!

**Comment by jhermann** [comment]
The .env call is the culprit, you do not need those *host* packages when you init the workdir's venv.

This is so “natural and obvious” to me, I failed to mention it. ;)

**Comment by jhermann** [comment]
You were right about `debhelper` though.

**Comment by stegro** [comment]
Thank you @jhermann for packaging, clarifying that and helping.
